### ISSUE TITLE
feat: UI redesign - vscode alignment

### ISSUE THREAD

**Issue by lcotterffdc** [financialforcedev/debug-log-analyzer#247]
### Is your feature request related to a problem?

We should align the style of our UI to vscode

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] New menu bar
- [ ] Skelton loading UI
- [ ] Add icons to commands 
- [ ] Restyle links
```
